USE `md8id2hgb8635iss`;

DROP TABLE IF EXISTS `app_user`;
CREATE TABLE app_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,    
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(1000) NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    is_admin BOOLEAN  NOT NULL DEFAULT FALSE
);



DROP TABLE IF EXISTS `user`;
CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,    
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(1000) NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    is_admin BOOLEAN  NOT NULL DEFAULT FALSE
);

